Update the Code to Use boto 3
jcjohnson/simple-amt pull request #28
Opened 2019-07-28 16:25 UTC by yangky11

Related to this [issue](https://github.com/jcjohnson/simple-amt/issues/27).

Not finished yet, but `launch_hits.py` has been fixed.

2019-07-28 19:31 UTC, yangky11 commented
Finished an edit pass through all files. 
Haven't tested yet.

2019-07-28 21:11 UTC, yangky11 commented
Squashed into 1 commit and ready to be merged.
Small bugs may exist but should be easy to fix later.

2019-07-31 17:32 UTC, jcjohnson requested changes
Looks great -- thanks for updating this! Please address a couple minor comments and I'll merge.

2019-07-31 17:32 UTC, jcjohnson commented on README.md
> +- `fFrame_height`: Required. Must be an integer. When you HIT is displayed, Amazon renders the HIT content inside of an iframe. The height of the iframe is `Frame_height` pixels. You should pick a nu
Is this a typo?

2019-07-31 17:32 UTC, jcjohnson commented on README.md
> +- `Hits_approved`: Optional. Must be an integer. If you set this, then only workers who have had at least this many HITs approved on Mechanical Turk will be allowed to work on your assignments.
Can you change to `HitsApproved` for consistent camel case on the properties file? Also same comment for the fields below.

2019-07-31 17:32 UTC, jcjohnson commented on approve_hits.py
> +            # Try to parse the output from the assignment. If it isn't
Indent the comment to match the code it describes

2019-08-01 03:05 UTC, yangky11 commented
Thanks for the comments. I have fixed them.

2019-09-24 15:15 UTC, jcjohnson commented
Is this ready to merge now?

2019-09-24 15:17 UTC, yangky11 commented
yes

2019-09-24 15:18 UTC, merged

2019-09-24 15:18 UTC, jcjohnson commented
Thanks!